# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.create(email: "admin@admin", clinic_owner: false, password: '123456', password_confirmation: '123456')
User.create(email: "clinica@clinica", clinic_owner: true, password: '123456', password_confirmation: '123456')
User.create(email: "clinica2@clinica2", clinic_owner: true, password: '123456', password_confirmation: '123456')
User.create(email: "user@user", clinic_owner: false, password: '123456', password_confirmation: '123456')
User.create(email: "user2@user2", clinic_owner: false, password: '123456', password_confirmation: '123456')


User.create(email: "1@1", clinic_owner: true, password: '123456', password_confirmation: '123456')
User.create(email: "2@2", clinic_owner: true, password: '123456', password_confirmation: '123456')
User.create(email: "3@3", clinic_owner: true, password: '123456', password_confirmation: '123456')
User.create(email: "4@4", clinic_owner: true, password: '123456', password_confirmation: '123456')
User.create(email: "5@5", clinic_owner: true, password: '123456', password_confirmation: '123456')
User.create(email: "6@6", clinic_owner: true, password: '123456', password_confirmation: '123456')
User.create(email: "7@7", clinic_owner: true, password: '123456', password_confirmation: '123456')
User.create(email: "8@8", clinic_owner: true, password: '123456', password_confirmation: '123456')



Clinic.create(name:"Zé Gotinha", address: "Rua Roma n° 673, Jardim Augusta, São José dos Campos", user: User.find_by(email:'clinica@clinica'))

Clinic.create(name:"Imunolife UNIDADE ED. DR. CRISPIM", address: "SMHN Qd. 02 Ed. Dr. Crispim – salas 605 / 606 Asa Norte Brasilia -DF", user: User.find_by(email:'1@1'))
Clinic.create(name:"Imunolife UNIDADE LAGO SUL", address: "SHIS QI 15 Ed. Victoria Medical Center sala T-14 A Lago Sul -Brasilia -DF", user: User.find_by(email:'2@2'))
Clinic.create(name:"Imunocentro ASA NORTE", address: "STN Bloco M Sala 310 - Edifício Vital Brazil - Brasília - DF", user: User.find_by(email:'3@3'))
Clinic.create(name:"Imunocentro ASA SUL", address: "SEPS 715/915 Bloco D Sala 510 - Centro Clínico Pacini - Brasília - DF", user: User.find_by(email:'4@4'))
Clinic.create(name:"Prime Vacinas Unidade 01", address: "SMHN Quadra 02. Bloco B. Sala 205. Edifício Cléo Octávio. Asa Norte. Brasília-DF.", user: User.find_by(email:'5@5'))
Clinic.create(name:"Prime Vacinas Unidade 02", address: "SHLS 716 Conjunto L. Torre II. Sala 22.Centro Clínico Sul. Asa Sul. Brasília-DF.", user: User.find_by(email:'6@6'))
Clinic.create(name:"Prime Vacinas Filial Águas Claras", address: "Avenida das Araucárias lote 1835 a 2005. Águas Claras Shopping Sala 437. Brasília-DF.", user: User.find_by(email:'7@7'))
Clinic.create(name:"CLIDIP", address: "SEPS 710/910 Sul - Centro Clínico Via Brasil, Torre B, Sala 536. Brasília, DF.", user: User.find_by(email:'8@8'))


VaccineType.create(name:'Vacina BCG', description: 'O que previne:Tuberculose – principalmente as formas graves, como meningite tuberculosa e tuberculose miliar (espalhada pelo corpo).Do que é feita:É composta pelo bacilo de Calmette-Guérin – origem do nome BCG – obtido pela atenuação (enfraquecimento) de uma das bactérias que causam a tuberculose. Completam sua composição o glutamato de sódio e a solução fisiológica (soro a 0,9%).Indicação:A vacina é indicada de rotina a partir do nascimento até antes de a criança completar 5 anos de idade.')
VaccineType.create(name:'Vacina dengue', description: 'O que previneInfecção causada pelos quatro sorotipos de dengue: DEN1, DEN2, DEN3 e DEN4. A eficácia na prevenção da doença é de 65,5%; na prevenção de dengue grave e hemorrágica é de 93% e de internação é de mais de 80%.Do que é feitaTrata-se de vacina atenuada, composta pelos quatro sorotipos vivos do vírus dengue, obtidos separadamente por tecnologia de DNA recombinante. Contém ainda aminoácidos essenciais (incluindo fenilalanina), aminoácidos não essenciais, cloridrato de arginina, sacarose, trealose di-hidratada, sorbitol, trometamol e ureia. O diluente é constituído por cloreto de sódio e água para injeções. Não contém adjuvantes e conservantes.IndicaçãoA vacina está licenciada para crianças a partir de 9 anos de idade, adolescentes e adultos até 45 anos e é recomendada para indivíduos previamente infectados por um dos vírus da dengue (soropositivos com ou sem história da doença).')
VaccineType.create(name:'Vacina dupla bacteriana do tipo adulto – dT', description: 'O que previne:Difteria e tétano.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.Contém toxoides diftérico e tetânico, derivados das toxinas produzidas pelas bactérias causadoras das doenças; tem o sal de alumínio como adjuvante, cloreto de sódio, e água para injeção.Indicações:')
VaccineType.create(name:'Vacina dupla bacteriana infantil – DT', description: 'O que previne:Difteria e tétano.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.Contém toxoides diftérico e tetânico, derivados das toxinas produzidas pelas bactérias causadoras das doenças, sal de alumínio como adjuvante, cloreto de sódio, e água para injeção.Indicação:')
VaccineType.create(name:'Vacina tríplice bacteriana acelular do tipo adulto – dTpa', description: 'O que previne:Difteria, tétano e coqueluche.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.Contém os toxoides diftérico e tetânico (derivados das toxinas produzidas pelas bactérias causadoras das doenças), e componentes da cápsula da bactéria da coqueluche (Bordetella pertussis), sal de alumínio como adjuvante, fenoxietanol, cloreto de sódio e água para injeção.A quantidade de toxoide diftérico e de componentes pertussis é menor que na vacina infantil (DTPa).')
VaccineType.create(name:'Vacina tríplice bacteriana acelular infantil – DTPa', description: 'O que previne:Difteria, tétano e coqueluche.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.Contém os toxoides diftérico e tetânico (derivados das toxinas produzidas pelas bactérias causadoras das doenças), e componentes da cápsula da bactéria da coqueluche (Bordetella pertussis), sal de alumínio como adjuvante, fenoxietanol, cloreto de sódio, e água para injeção.Indicações:')
VaccineType.create(name:'Vacina tríplice bacteriana acelular do tipo adulto com poliomielite – dTpa-VIP', description: 'O que previne:Difteria, tétano, coqueluche e poliomielite.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.Contém os toxoides diftérico e tetânico (derivados das toxinas produzidas pelas bactérias causadoras das doenças), componentes da cápsula da bactéria da coqueluche (Bordetella pertussis), vírus da poliomielite inativados (mortos) tipos 1, 2 e 3, sal de alumínio como adjuvante, 2-fenoxietanol, polissorbato 80, cloreto de sódio e água para injeção.Pode conter ainda traços de formaldeído, neomicina e polimixina B usados no processo de fabricação.')
VaccineType.create(name:'Vacina tríplice bacteriana de células inteiras – DTPw', description: 'O que previne:Difteria, tétano e coqueluche.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.Contém os toxoides diftérico e tetânico (derivados das toxinas produzidas pelas bactérias causadoras das doenças); bactéria morta da coqueluche (Bordetella pertussis); sal de alumínio como adjuvante, cloreto de sódio, e água para injeção.Indicações:')
VaccineType.create(name:'Vacina tríplice bacteriana de células inteiras combinada com Hib e hepatite B (DTPw­-HB/Hib)', description: 'O que previne:Difteria, tétano, coqueluche, meningite por Hib (bactéria Haemophilus influenzae tipo b) e hepatite B.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.É composta por toxoides diftérico e tetânico, combinados com a célula inteira purificada da bactéria da coqueluche (Bordetela pertussis); partícula da superfície do vírus da hepatite B (HBsAg) e componente da cápsula do Haemophilus influenzae tipo b (Hib), conjugado com uma proteína. Contém também fosfato de alumínio, cloreto de sódio e água para injeção.Indicação:')
VaccineType.create(name:'Vacinas combinadas à DTPa', description: 'O que previne:Do que é feita:Tratam-se de vacinas inativadas, portanto, não têm como causar doença.DTPa-VIP/Hib: Além dos componentes da vacina tríplice bacteriana acelular (DTPa), contém componente da bactéria Haemophilus influenzae tipo b conjugado e vírus inativados (mortos) da poliomielite tipos 1, 2 e 3. A composição inclui ainda: lactose, cloreto de sódio, 2-fenoxietanol, hidróxido de alumínio e água para injeção. Pode conter traços de antibiótico (estreptomicina, neomicina e polimixina B), formaldeído e soroalbumina de origem bovina.DTPa-VIP-HB/Hib: Além dos componentes da vacina tríplice bacteriana acelular (DTPa), contém componente da bactéria Haemophilus influenzae tipo b conjugado, vírus inativados (mortos) da poliomielite tipos 1, 2 e 3 e componente da superfície do vírus da hepatite B. A composição inclui ainda: lactose, cloreto de sódio, 2-fenoxietanol, hidróxido de alumínio e água para injeção. Pode conter traços de antibiótico (estreptomicina, neomicina e polimixina B), formaldeído e soroalbumina de origem bovina.Indicação:')
VaccineType.create(name:'Vacina febre amarela – FA', description: 'O que previne:Febre amarela.Do que é feita:No Brasil estão disponíveis duas vacinas: a produzida por Bio-Manguinhos – Fiocruz, utilizada pela rede pública, e a produzida pela Sanofi Pasteur, utilizada pelos serviços privados de vacinação e eventualmente pela rede pública. Ambas são elaboradas a partir de vírus vivo atenuado, cultivado em ovo de galinha. A vacina de Biomanguinhos apresenta em sua formulação gelatina bovina, eritromicina, canamicina, cloridrato de L-histidina, L-alanina, cloreto de sódio e água para injeção. Já a da Sanofi Pasteur contém: lactose, sorbitol, cloridrato de L-histidina, L-alanina e solução salina.As duas têm perfis de segurança e eficácia semelhantes, estimados em mais de 95% para maiores de 2 anos.É importante ressaltar que os estudos para o uso de doses fracionadas, recomendado apenas durante campanhas do Ministério da Saúde, em localidades e períodos bem definidos, foram realizados apenas com a vacina de Bio-Manguinhos. Não há, portanto, autorização para a administração de doses fracionadas da vacina da Sanofi Pasteur.')
VaccineType.create(name:'Vacina febre tifoide', description: 'O que previne:Febre tifoide.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.É composta por polissacarídeos da cápsula da bactéria (Salmonella typhi), fenol, cloreto de sódio, fosfato dissódico diidratado, fosfato monossódico diidratado e água para injeção.Indicação:')
VaccineType.create(name:'Vacina gripe (influenza) — trivalente ou quadrivalente', description: 'O que previne:Infecção pelo vírus Influenza (que causa a gripe) contidos nas vacinas.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.Sua formulação contém proteínas de diferentes cepas do vírus Influenza definidas ano a ano conforme orientação da Organização Mundial da Saúde (OMS), que realiza a vigilância nos hemisférios Norte e Sul. As cepas vacinais são cultivadas em ovos embrionados de galinha e, por isso, as vacinas contêm traços de proteínas do ovo.Existe vacina trivalente, com duas cepas de vírus A e uma cepa de vírus B, e vacina quadrivalente, com duas cepas de vírus A e duas cepas de vírus B.')
VaccineType.create(name:'Vacina hepatite A', description: 'O que previne:Hepatite A.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.É composta por antígeno do vírus da hepatite A, sal de alumínio amorfo, estabilizante (varia conforme o fabricante), cloreto de sódio a 0,9%. Pode conter traços de antibiótico (neomicina), fenoxietanol e formaldeído.Nos serviços privados de vacinação estão disponíveis as apresentações pediátrica (para uso até 15, 17 ou 19 anos de idade, dependendo do fabricante) e de adultos.')
VaccineType.create(name:'Vacina hepatite B', description: 'O que previne:Infecção do fígado (hepatite) causada pelo vírus da hepatite B.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.É composta por proteína de superfície do vírus da hepatite B purificado, hidróxido de alumínio, cloreto de sódio e água para injeção. Pode conter fosfato de sódio, fosfato de potássio e borato de sódio.A rede pública utiliza a apresentação multidose (mais de uma dose por frasco), que contém timerosal (derivado do mercúrio) como conservante.')
VaccineType.create(name:'Vacina combinada hepatite A e B', description: 'O que previne:Infecções do fígado (hepatites) causadas pelos vírus da hepatite A e hepatite B.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.É composta do vírus inativado (morto) da hepatite A e da proteína de superfície do vírus da hepatite B. Também possui em sua composição: sais de alumínio, formaldeído, sulfato de neomicina, fenoxietanol, polissorbato 20, cloreto de sódio e água para injeção.Indicação:')
VaccineType.create(name:'Vacina herpes zóster', description: 'O que previne:O herpes zóster, popularmente conhecido como “cobreiro”, e sua principal complicação, a neuropatia pós-herpética, responsável por dor crônica, prolongada, de difícil controle e extremamente debilitante.Do que é feita:Trata-se de vacina composta por vírus vivos atenuados da varicela zóster (VVZ) da cepa Oka/Merck, sacarose, gelatina, ureia, cloreto de sódio, levoglutamato de sódio monoidratado, fosfato de sódio dibásico, fosfato de potássio monobásico, cloreto de potássio, traços de neomicina e de soro de bezerro e água para injeção. Não contém conservantes.Indicação:A vacina está licenciada para pessoas com 50 anos ou mais e é recomendada como rotina para maiores 60 anos de idade.')
VaccineType.create(name:'Vacina Haemophilus influenzae tipo b – Hib', description: 'O que previne:Doenças causadas pelo Haemophilus influenzae tipo b, principalmente meningite.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.É composta de pó liofilizado com polissacarídeo da cápsula da bactéria Haemophilus influenzae tipo b (Hib) conjugado com toxoide tetânico, lactose, cloreto de sódio, água para injeção. As apresentações multidose contêm fenol. Na vacina disponível na rede pública há timerosal (derivado do mercúrio).Pode ser encontrada isolada ou combinada com a vacina tríplice bacteriana (DTPw ou DTPa).')
VaccineType.create(name:'Vacina HPV2', description: 'O que previne:Infecções persistentes e lesões pré-cancerosas causadas pelos tipos de HPV 16 e 18. É indicada para a prevenção de diversos tipos de câncer, em especial o de colo de útero.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.É composta pelas proteínas L1 do papilomavírus humano (HPV) tipos 16 e 18, 3-O-desacil-4 monofosforil lipídio A (MPL), alumínio, cloreto de sódio, fosfato de sódio monobásico diidratado e água para injeção.Indicação:')
VaccineType.create(name:'Vacina HPV4', description: 'O que previne:Infecções persistentes e lesões pré-cancerosas causadas pelos tipos de HPV 6,11,16,18. Também previne o câncer de colo do útero, da vulva, da vagina, do ânus e verrugas genitais (condiloma).Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.É composta pelas proteínas L1 dos papilomavírus humano (HPV) tipos 6,11,16,18, sulfato de hidroxifosfato de alumínio, cloreto de sódio, L-histidina, polissorbato 80, borato de sódio e água para injeção.Indicação:')
VaccineType.create(name:'Vacina meningocócica B', description: 'O que previne:Meningites e infecções generalizadas (doenças meningocócicas) causadas pela bactéria meningococo do tipo B.Do que é feita:Trata-se de vacina inativada, portanto, não causa infecção.É composta por quatro componentes (três proteínas subcapsulares e vesículas da membrana externa do meningococo B), além de hidróxido de alumínio, cloreto de sódio, histidina, sacarose e água para injeção.Indicação:')
VaccineType.create(name:'Vacina meningocócica C conjugada', description: 'O que previne:Doenças causadas pelo meningococo C (incluindo meningite e meningococcemia).Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença .Contém antígeno formado por componente da cápsula da bactéria (oligossacarídeo) do sorogrupo C conjugado a uma proteína que, dependendo do fabricante, pode ser o toxoide tetânico ou o mutante atóxico da toxina diftérica, chamado CRM 197. Contém também adjuvante hidróxido de alumínio, manitol, fosfato de sódio monobásico monoidratado, fosfato de sódio dibásico heptaidratado, cloreto de sódio e água para injeção.Indicação:')
VaccineType.create(name:'Vacina Meningocócica conjugada quadrivalente — ACWY', description: 'O que previne:Meningites e infecções generalizadas (doenças meningocócicas) causadas pela bactéria meningococo dos tipos A, C, W e Y.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.Contém antígenos das cápsulas dos meningococos dos sorogrupos A, C, W e Y conjugados a uma proteína que, dependendo do fabricante, pode ser o toxoide tetânico, diftérico, ou o mutante atóxico da toxina diftérica, chamado CRM-197. Pode conter também sacarose; trometamol; fosfato de potássio diidrogenado; cloreto de sódio; fosfato de sódio diidrogenado monoidratado; fosfato dissódico hidrogenado diidratado; cloreto de sódio e água para injeção.Indicação:')
VaccineType.create(name:'Vacina pneumocócica polissacarídica 23-valente – VPP23', description: 'O que previne:Doenças causadas por 23 tipos de pneumococos.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.É composta de partículas purificadas (polissacarídeos) das cápsulas de 23 tipos de Streptococos pneumoniae (pneumococo), cloreto de sódio, água para injeção e fenol.Indicação:')
VaccineType.create(name:'Vacinas pneumocócicas conjugadas', description: 'O que previnem:A vacina pneumocócica conjugada 10-valente (VPC10) previne cerca de 70% das doenças graves (pneumonia, meningite, otite) em crianças, causadas por dez sorotipos de pneumococos.A vacina pneumocócica conjugada 13-valente (VPC13) previne cerca de 90% das doenças graves (pneumonia, meningite, otite) em crianças, causadas por 13 sorotipos de pneumococos.Do que são feitas:Tratam-se de vacinas inativadas, portanto não têm como causar as doenças.A VPC10 é composta de dez sorotipos de Streptococcus pneumoniae (pneumococo), oito deles conjugados com a proteína D do Haemophilus influenzae tipo b, um com o toxoide tetânico e outro com toxoide diftérico. Contém também cloreto de sódio, fosfato de alumínio e água para injeção.')
VaccineType.create(name:'Vacinas poliomielite', description: 'O que previne:Poliomielite (paralisia infantil).Do que é feita:Vacina Oral Poliomielite (VOP) – É uma vacina oral atenuada bivalente, ou seja, composta pelos vírus da pólio tipos 1 e 3, vivos, mas “enfraquecidos”. Contém ainda cloreto de magnésio, estreptomicina, eritromicina, polissorbato 80, L-arginina e água destilada.Vacina Inativada Poliomielite (VIP) – Por ser inativada, não tem como causar a doença. É uma vacina trivalente e injetável, composta por partículas dos vírus da pólio tipos 1, 2 e 3. Contém ainda 2-fenoxietanol, polissorbato 80, formaldeído, meio Hanks 199, ácido clorídrico ou hidróxido de sódio. Pode conter traços de neomicina, estreptomicina e polimixina B, utilizados durante a produção.Indicação:')
VaccineType.create(name:'Vacina raiva', description: 'O que previne:Raiva.Do que é feita:Trata-se de vacina inativada, portanto, não tem como causar a doença.Contém vírus inativados (mortos) da raiva, maltose, albumina humana, cloreto de sódio e água para injeção. Pode conter traços de estreptomicina, neomicina e polimixina B, antibióticos usados no cultivo do vírus vacinal.Indicação:')
VaccineType.create(name:'Vacina rotavírus', description: 'O que previne:Doença diarreica causada por rotavírus.Do que é feita:Vacina oral monovalente (VRH1) contém um tipo de rotavírus vivo “enfraquecido”, além de sacarose, adipatodissódico, meio Eagle modificado Dulbecco (DMEM) e água estéril.Vacina oral atenuada pentavalente (VRH5) é composta por cinco tipos de rotavírus vivos “enfraquecidos”, sacarose, citrato de sódio, fosfato de sódio monobásico monoidratado, hidróxido de sódio, polissorbato 80, meios de cultura e traços de soro fetal bovino.Indicação:')
VaccineType.create(name:'Vacina tríplice viral (sarampo, caxumba e rubéola) – SCR', description: 'O que previne:Sarampo, caxumba e rubéola.Do que é feita:Trata-se de vacina atenuada, contendo vírus vivos “enfraquecidos” do sarampo, da rubéola e da caxumba; aminoácidos; albumina humana; sulfato de neomicina; sorbitol e gelatina. Contém também traços de proteína do ovo de galinha usado no processo de fabricação da vacina.No Brasil, uma das vacinas utilizadas na rede pública contém traços de lactoalbumina (proteína do leite de vaca).Indicação:')
VaccineType.create(name:'Vacina tetraviral (sarampo, caxumba, rubéola e varicela) – SCR-V', description: 'O que previne:Sarampo, caxumba, rubéola e varicela.Do que é feita:Trata-se de vacina atenuada, contendo vírus vivos “enfraquecidos” do sarampo, da rubéola, da caxumba e da varicela (catapora), lactose anidra, sorbitol, manitol, aminoácidos, traços de neomicina e água para injeção. Contém traços de proteína do ovo de galinha usado no processo de fabricação da vacina.Indicação:Contraindicação:')
VaccineType.create(name:'Vacina varicela (catapora)', description: 'O que previne:Varicela (catapora).Do que é feita:Trata-se de vacina atenuada, contendo vírus vivos “enfraquecidos” da varicela, além de gelatina, traços de neomicina, água para injeção. Não contém traços de proteína do ovo de galinha.Indicação:Contraindicação:')
VaccineType.create(name:'Palivizumabe', description: 'O palivizumabe não é uma vacina, mas uma imunoglobulina – um tipo de anticorpo "pronto" que induz imunização passiva específica contra o vírus sincicial respiratório (VSR). Está incluído aqui porque é a única forma disponível, hoje, para a prevenção de quadros graves de infecções respiratórias em lactentes, como a bronquiolite e, principalmente, pneumonias. Até o momento não dispomos de vacinas contra o VSR.O que previneAs formas graves de infecção pelo vírus sincicial respiratório (VSR), em bebês de alto risco.Do que é feitoTrata-se de um anticorpo específico contra o VSR, elaborado por técnica de engenharia genética (imunização passiva).Indicação')

# VaccineType.create(name:"Febre Amarela", description: "Vacina para febre amarela, Validade: 10 anos")
# VaccineType.create(name:"Tríplice Bacteriana (DTP)", description: "Vacina para difteria, tétano e coqueluche, Validade: 5 anos")
# VaccineType.create(name:"Gripe", description: "Vacina para gripe, Validade: 1 ano")

Vaccine.create(price:300.00, vaccine_type: VaccineType.find_by(name:"Vacina BCG"), clinic: Clinic.find_by(name:"Zé Gotinha"))


Vaccine.create(price:300.00, vaccine_type: VaccineType.find_by(name:"Vacina BCG"), clinic: Clinic.find_by(name:"Zé Gotinha"))
Vaccine.create(price:200.00, vaccine_type: VaccineType.find_by(name:"Vacina dengue"), clinic: Clinic.find_by(name:"Zé Gotinha"))
Vaccine.create(price:150.00, vaccine_type: VaccineType.find_by(name:"Vacina BCG"), clinic: Clinic.find_by(name:"CLIDIP"))
Vaccine.create(price:100.00, vaccine_type: VaccineType.find_by(name:"Vacina dengue"), clinic: Clinic.find_by(name:"CLIDIP"))
Vaccine.create(price:50.00, vaccine_type: VaccineType.find_by(name:"Vacina gripe (influenza) — trivalente ou quadrivalente"), clinic: Clinic.find_by(name:"CLIDIP"))

Order.create(unit_price: 300.00, quantity: 2,
             vaccine: Vaccine.find_by( vaccine_type: VaccineType.find_by(name:"Vacina BCG"), 
                                       clinic: Clinic.find_by(name:"Zé Gotinha")), user: User.find_by(email: "user@user"))
Order.create(unit_price: 50.00,  quantity: 3,
             vaccine: Vaccine.find_by( vaccine_type: VaccineType.find_by(name:"Vacina gripe (influenza) — trivalente ou quadrivalente"), 
                                       clinic: Clinic.find_by(name:"CLIDIP")), user: User.find_by(email: "user2@user2"))

Review.create(description: " Nem doeu. ", stars: 5, order: Order.first)
Review.create(description: " Aplicação profissional. ", stars: 5, order: Order.first)
Review.create(description: " Horrível. Não se vacine nessa clínica. ", stars: 0, order: Order.first)
Review.create(description: " Doeu um pouco, mas é uma ótima clinica. ", stars: 3, order: Order.all[1])